//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCartMVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTransaction
    {
        public int TransID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> pid { get; set; }
        public Nullable<int> qty { get; set; }
    
        public virtual ProductInfo ProductInfo { get; set; }
        public virtual OrderInfo OrderInfo { get; set; }
    }
}
