//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCartMVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInfo
    {
        public OrderInfo()
        {
            this.OrderTransactions = new HashSet<OrderTransaction>();
        }
    
        public int OrderId { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<decimal> TotAmount { get; set; }
        public string Status { get; set; }
    
        public virtual PersonInfo PersonInfo { get; set; }
        public virtual ICollection<OrderTransaction> OrderTransactions { get; set; }
    }
}
