//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCartMVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonInfo
    {
        public PersonInfo()
        {
            this.OrderInfoes = new HashSet<OrderInfo>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<long> mobno { get; set; }
        public string password { get; set; }
        public string type { get; set; }
    
        public virtual ICollection<OrderInfo> OrderInfoes { get; set; }
    }
}
